rdrf/explorer/urls.py
from django.conf.urls import patterns, url
from explorer.views import MainView
from explorer.views import QueryView, NewQueryView
from explorer.views import DeleteQueryView, DownloadQueryView
from explorer.views import SqlQueryView

urlpatterns = patterns(
    '',
    url(r'^query/(?P<query_id>\w+)/?$',
        QueryView.as_view(), name='explorer_query'),
    url(r'^query/download/(?P<query_id>\w+)?/(?P<action>\w+)?/?$',
        DownloadQueryView.as_view(), name='explorer_query_download'),
    url(r'^query/delete/(?P<query_id>\w+)/?$',
        DeleteQueryView.as_view(), name='explorer_query_delete'),

    url(r'^sql$',
        SqlQueryView.as_view(), name='explorer_sql_query'),

    url(r'^new$', NewQueryView.as_view(), name='explorer_new'),

    url(r'$', MainView.as_view(), name='explorer_main'),
)

rdrf/rdrf/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.shortcuts import render_to_response
from django.views.generic.base import TemplateView

import registry.urls as common_urls
from rdrf import api_urls
import rdrf.form_view as form_view
import rdrf.registry_view as registry_view
import rdrf.landing_view as landing_view
import rdrf.import_registry_view as import_registry_view
import rdrf.patient_view as patient_view
import rdrf.login_router as login_router
import rdrf.report_view as report_view
import rdrf.consent_view as consent_view
from rdrf.registration_rdrf import RdrfRegistrationView
from rdrf.registry_list_view import RegistryListView
from rdrf.lookup_views import FamilyLookup
from rdrf.lookup_views import PatientLookup
from rdrf.views import RegistryList
from registry.patients.views import update_session
from registration.backends.default.views import ActivationView
from rdrf.family_linkage import FamilyLinkageView
from rdrf.trans_view import TranslationView
from rdrf.trans_view import TranslationViewReload
from rdrf.email_notification_view import ResendEmail
from rdrf.permission_matrix import PermissionMatrixView
from rdrf.lookup_views import UsernameLookup
from rdrf.lookup_views import RDRFContextLookup
from rdrf.lookup_views import RecaptchaValidator
from rdrf.context_views import RDRFContextCreateView, RDRFContextEditView
from rdrf import patients_listing

from ajax_select import urls as ajax_select_urls


# very important so that registry admins (genetic, patient, etc) are discovered.
admin.autodiscover()


def handler404(request):
    return render_to_response("404.html")


def handler500(request):
    return render_to_response("500.html")


def handlerApplicationError(request):
    return render_to_response(
        "rdrf_cdes/application_error.html", {"application_error": "Example config Error"})


urlpatterns = patterns('',
                       url(r'^test404', handler404),
                       url(r'^test500', handler500),
                       url(r'^testAppError', handlerApplicationError),
                       url(r'^iprestrict', include('iprestrict.urls')),
                       url(r'^useraudit', include('useraudit.urls')),

                       (r'^api/v1/', include(api_urls, namespace='v1')),
                       # (r'^api/v2/', include(api_urls, namespace='v2')), etc.

                       url(r'^constructors/(?P<form_name>\w+)/?$',
                           form_view.ConstructorFormView.as_view(), name="constructors"),
                       url(r'^rpc', form_view.RPCHandler.as_view(), name='rpc'),

                       (r'^admin/', include(admin.site.urls)),
                       (r'', include('django.contrib.auth.urls')),
                       (r'', include(common_urls, namespace="registry")),

                       url(r'^/?$', landing_view.LandingView.as_view(), name='landing'),
                       url(r'^reglist/?', RegistryListView.as_view(), name="reglist"),
                       url(r'^import/?', import_registry_view.ImportRegistryView.as_view(),
                           name='import_registry'),
                       url(r'^reports/?', report_view.ReportView.as_view(), name="reports"),
                       url(r'^reportdatatable/(?P<query_model_id>\d+)/?$', report_view.ReportDataTableView.as_view(),
                           name="report_datatable"),
                       url(r'^explorer/', include('explorer.urls')),
                       url(r'^listregistry/?$', RegistryList.as_view(), name='registry_list'),
                       url(r'^patientslisting/?', patients_listing.PatientsListingView.as_view(),
                           name="patientslisting"),
                       url(r'^contexts/(?P<registry_code>\w+)/(?P<patient_id>\d+)/add/(?P<context_form_group_id>\d+)?$',
                           RDRFContextCreateView.as_view(),
                           name="context_add"),
                       url(r'contexts/(?P<registry_code>\w+)/(?P<patient_id>\d+)/(?P<context_id>\d+)/edit/?$',
                           RDRFContextEditView.as_view(),
                           name="context_edit"),
                       url(r'^login/?$', 'django.contrib.auth.views.login',
                           {'template_name': 'admin/login.html'}, name='login'),
                       url(r'^router/', login_router.RouterView.as_view(), name="login_router"),

                       url(r"^(?P<registry_code>\w+)/forms/(?P<form_id>\w+)/(?P<patient_id>\d+)/(?P<context_id>add)/?$",
                           form_view.FormView.as_view(), name='form_add'),

                       url(r"^(?P<registry_code>\w+)/forms/(?P<form_id>\w+)/(?P<patient_id>\d+)/(?P<context_id>\d+)?$",
                           form_view.FormView.as_view(), name='registry_form'),

                       url(r"^(?P<registry_code>\w+)/forms/print/(?P<form_id>\w+)/(?P<patient_id>\d+)/(?P<context_id>\d+)?$",
                           form_view.FormPrintView.as_view(), name='registry_form_print'),

                       url(r"^(?P<registry_code>\w+)/forms/(?P<form_id>\w+)/(?P<patient_id>\d+)/(?P<section_code>\w+)/(?P<context_id>\d+)?/(?P<cde_code>\w+)/history/?$",
                           form_view.FormFieldHistoryView.as_view(), name='registry_form_field_history'),

                       url(r"^(?P<registry_code>\w+)/?$",
                           registry_view.RegistryView.as_view(), name='registry'),

                       url(r"^(?P<registry_code>\w+)/patient/add/?$",
                           patient_view.AddPatientView.as_view(), name='patient_add'),

                       url(r"^(?P<registry_code>\w+)/patient/(?P<patient_id>\d+)/edit$",
                           patient_view.PatientEditView.as_view(), name='patient_edit'),

                       url(r"^(?P<registry_code>\w+)/permissions/?$",
                           PermissionMatrixView.as_view(), name='permission_matrix'),

                       #---- Consent related URLs -----------------
                       url(r"^(?P<registry_code>\w+)/consent/?$",
                           consent_view.ConsentList.as_view(), name='consent_list'),

                       url(r"^(?P<registry_code>\w+)/consent/(?P<section_id>\d+)/(?P<patient_id>\d+)/?$",
                           consent_view.ConsentDetails.as_view(), name='consent_details'),

                       url(r"^(?P<registry_code>\w+)/consent/print/?$",
                           consent_view.PrintConsentList.as_view(), name='print_consent_list'),

                       url(r"^(?P<registry_code>\w+)/(?P<patient_id>\d+)/consents/?$",
                           form_view.CustomConsentFormView.as_view(), name="consent_form_view"),

                       url(r"^(?P<registry_code>\w+)/(?P<patient_id>\d+)/consents/print/?$",
                           consent_view.ConsentDetailsPrint.as_view(), name="print_consent_details"),

                       #-------------------------------------------

                       #---- Email Notifications URLs -------------
                       url(r"^resend_email/(?P<notification_history_id>\w+)/?$",
                           ResendEmail.as_view(), name="resend_email"),
                       #-------------------------------------------

                       url(r"^(?P<registry_code>\w+)/familylinkage/(?P<initial_index>\d+)?$",
                           FamilyLinkageView.as_view(), name='family_linkage'),

                       url(r'^(?P<registry_code>\w+)/questionnaire/(?P<questionnaire_context>\w+)?$',
                           form_view.QuestionnaireView.as_view(), name='questionnaire'),
                       url(r'^(?P<registry_code>\w+)/approval/(?P<questionnaire_response_id>\d+)/?$', form_view.QuestionnaireHandlingView.as_view(),
                           name='questionnaire_response'),
                       url(r'^(?P<registry_code>\w+)/uploads/(?P<file_id>([0-9a-fA-F]{24})|(\d+))$',
                           form_view.FileUploadView.as_view(), name='file_upload'),
                       (r'^admin/lookups/', include(ajax_select_urls)),

                       url(r'^admin/patients/updatesession/?$',
                           update_session, name='updatesession'),
                       url(r'^questionnaireconfig/(?P<form_pk>\d+)/?$',
                           form_view.QuestionnaireConfigurationView.as_view(), name='questionnaire_config'),
                       url(r'^designer/(?P<reg_pk>\d+)$',
                           form_view.RDRFDesigner.as_view(), name='rdrf_designer'),
                       url(r'^cdes', form_view.RDRFDesignerCDESEndPoint.as_view(),
                           name='rdrf_designer_cdes_endpoint'),
                       url(r'^registrystructure/(?P<reg_pk>\d+)$', form_view.RDRFDesignerRegistryStructureEndPoint.as_view(),
                           name='rdrf_designer_registry_structure_endpoint'),
                       url(r'^adjudicationinitiation/(?P<def_id>\d+)/(?P<patient_id>\d+)/?$',
                           form_view.AdjudicationInitiationView.as_view(), name='adjudication_initiation'),
                       url(r'^adjudicationrequest/(?P<adjudication_request_id>\d+)/?$',
                           form_view.AdjudicationRequestView.as_view(), name='adjudication_request'),
                       url(r'^adjudicationresult/(?P<adjudication_definition_id>\d+)/(?P<requesting_user_id>\d+)/(?P<patient_id>\d+)/?$',
                           form_view.AdjudicationResultsView.as_view(), name='adjudication_result'),



                       url(r'api/familylookup/(?P<reg_code>\w+)/?$', FamilyLookup.as_view(), name="family_lookup"),
                       url(r'api/patientlookup/(?P<reg_code>\w+)/?$', PatientLookup.as_view(), name="patient_lookup"),

                       #---- Look-ups URLs -----------------------

rdrf/explorer/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError

from rdrf.models import Registry


class Query(models.Model):
    MONGO_SEARCH_TYPES = (
        ('C', 'Current'),
        ('L', 'Longitudinal'),
        ('M', 'Mixed'),
    )

    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    registry = models.ForeignKey(Registry)
    access_group = models.ManyToManyField(Group)

    mongo_search_type = models.CharField(max_length=1, choices=MONGO_SEARCH_TYPES, default='C')

    collection = models.CharField(max_length=255, default="cdes")
    criteria = models.TextField(blank=True, null=True)
    projection = models.TextField(blank=True, null=True)
    aggregation = models.TextField(blank=True, null=True)

    sql_query = models.TextField()
    created_by = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    max_items = models.IntegerField(default=3)  # max number of multisection items to show in datatable

    def get_absolute_url(self):
        return reverse('explorer_query', kwargs={'query_id': self.pk})

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Queries'

    def __unicode__(self):
        return unicode(self.title)

    def has_view(self):
        return self.mongo_search_type in ['C', 'L']

    def clean(self):
        if self.mongo_search_type == "M":
            errors = self._get_mixed_query_errors()
            if len(errors) > 0:
                error_string = ",".join(errors)
                raise ValidationError("Report Config Errors: %s" % error_string)

    def _get_mixed_query_errors(self):
        import json
        errors = []
        try:
            data = json.loads(self.sql_query)
            static_sheets = data["static_sheets"]
            for sheet in static_sheets:
                sheet_name = sheet["name"]
                columns = sheet["columns"]
                for column in columns:
                    if not isinstance(column, basestring):
                        errors.append("columns in sheet %s not all strings: %s" % (sheet_name, column))

        except ValueError as ve:
            errors.append("JSON malformed: %s" % ve.message)
        except KeyError as ke:
            errors.append("key error: %s" % ke.message)
        return errors

rdrf/explorer/forms.py
from django.forms import ModelForm
from models import Query


class QueryForm(ModelForm):

    class Meta:
        model = Query
        fields = [
            'id',
            'title',
            'description',
            'registry',
            'access_group',
            'collection',
            'criteria',
            'projection',
            'aggregation',
            'mongo_search_type',
            'sql_query',
            'max_items',
            'created_by'
        ]

rdrf/explorer/templates/explorer/base.html
<!DOCTYPE HTML>
{% load static from staticfiles %}
    
<html>
    <head>
        <title>RDRF Reporting Tool</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <script type="text/javascript" src="{% static 'js/vendor/codemirror-3.21.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jquery-1.11.3.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/jquery-ui-1.11.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap-3.1.1/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/vendor/underscore-1.5.2.min.js' %}"></script>
        
        <link rel="stylesheet" href="{% static 'css/jquery-1.11.4/themes/smoothness/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-3.1.1/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-3.1.1/css/bootstrap-theme.min.css' %}">

        <link rel="stylesheet" href="{% static 'css/explorer.css' %}">
        <script type="text/javascript" src="{% static 'js/rpc_module.js' %}"></script>
        
        <script type="text/javascript" src="{% static 'js/jquery.cookies.js' %}"></script>

        <script>
            var rpc = new RPC.RPC("{% url 'rpc' %}", "{{csrf_token}}");
        </script>
    </head>
    
    <body>
        
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <p class="navbar-brand" href="explorer">RDRF Reporting Tool <sup>{{version}}</sup></p>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'explorer_main' %}">List</a></li>
                    {% if request.user.is_superuser %}
                        <li><a href="{% url 'explorer_new' %}">New</a></li>
                    {% endif %}
                </ul>

                {% if status %}
                    <p class="navbar-text pull-right"><b><font color="green">Connected</font></p>
                {% else %}
                    <p class="navbar-text pull-right"><b><font color="red">Not connected</font></b></p>
                {% endif%}
            </div>
        </nav>
        
        <div class="container">
            <div class="alert alert-danger" id="response_error" style="display: none;"></div>
            {% if success_msg %}
                <div class="alert alert-success">{{success_msg}}</div>
            {% endif %}
    
            {% if error_msg %}
                <div class="alert alert-danger">{{error_msg}}</div>
            {% endif %}
            
			<!-- For Javascript errors -->
			<div id="js-errors" class="alert alert-danger" style="display: none"></div>
			
            {% block content %}
            {% endblock %}
        </div>

        <div id="footer">
            <div class="container">
                <h6 class="text-muted">Project developed at <a href="http://ccg.murdoch.edu.au" target="_blank">Centre for Comparative Genomics</a>, <a href="http://www.murdoch.edu.au" target="_blank">Murdoch University</a> &copy <script>document.write(new Date().getFullYear())</script></h6>
            </div>
        </div>
        
        <script>
            $(document).ready(function() {
                if('{{form.mongo_search_type.value}}' == 'F') {
                    $("#mongo-parameters-aggregation").hide();
                } else {
                    $("#mongo-parameters-find").hide();
                }
                
                $("#query-error").hide();
    
                $("#registry-option").change(function(){
                    $("#database").val(this.value);
                });
                
                $("#id_mongo_search_type").change(function() {
                    $("#mongo-parameters-aggregation").toggle();
                    $("#mongo-parameters-find").toggle();
                });

                $('#submit-query').click(function() {
                    $('#results-head').empty();
                    $('#results-body').empty();
                    $.post('', $("#query-form").serialize())
                        .error(function(xhr, textStatus, error) { 
                            $("#response_error").text(textStatus);
                            $("#response_error").fadeIn().delay(3000).fadeOut();
                        })
                        .done(function( data ) {
	                      if (data != "") {
                                 $("#response_error").text(data);
                                 $("#response_error").fadeIn().delay(3000).fadeOut();
	                      }
//                            var response = jQuery.parseJSON(data);
//                            if ($.isEmptyObject(response)) {
//                                $("#response_error").text("No results");
//                                $("#response_error").fadeIn().delay(3000).fadeOut();
//                                return;
//                            }
//
//                            $('#results-head').empty();
//                            $('#results-body').empty();
//
//                            $.each(response[0], function(key, value) {
//                                $('#results-head').append($("<th></th>").text(key));
//                            });
//
//                            $.each(response, function(key, value) {
//                                var row = $('<tr></tr>');
//                                $.each(value, function(key, value) {
//                                    if (value instanceof Array) {
//
//                                    }
//                                    row.append($('<td></td>').text(value));
//                                });
//                                $('#results-body').append(row);
//                            });
                    });
                });

                $('#hide-form-btn').click(function() {
                    $('#query-form-table').toggle("blind", function() {
                        if($('#query-form-table').is( ":visible" )) {
                            $('#hide-form-btn').html('Hide form');
                        } else {
                            $('#hide-form-btn').html('Show form');
                        }
                    });
                });
                
                $('#hide-description-btn').click(function() {
                    $('#query-description').toggle("blind", function() {
                        if($('#query-description').is( ":visible" )) {
                            $('#hide-description-btn').html('Hide description');
                        } else {
                            $('#hide-description-btn').html('Show description');
                        }
                    });
                });
                
                $('#sql-submit-query').click(function(){
                    $("#query-error").hide("blind");
                    $.ajax({
                        url: "{% url 'explorer_sql_query' %}",
                        type: "POST",
                        data: {
                            'sql_query': $('#sql_query').val(),
                            'registry': $('#id_registry').val(),
	                    'mongo_search_type': $('#id_mongo_search_type').val()
                        },
                        headers: {
                            'X-CSRFToken': $.cookie('{{ csrf_token_name }}')
                        },
                        success: function(data) {
                            response = jQuery.parseJSON(data);
                            if ("error_msg" in response) {
                                $('#query-result-count').empty();
                                $("#query-error").show('blind');
                                $("#query-error").html(response['error_msg']);
	                         
                             } else if ("success_msg" in response)  {
	                        $('#query-result-count').empty();
	                        $('#query-result-count').html(response['success_msg']);
	                    }
	    
	                    else {
                                $('#query-result-count').empty();
                                $('#query-result-count').html("Valid query | <strong>" + response.length + "</strong> record(s) found");
                            }
                        }
                    });
                });
            });
        </script>

    </body>
</html>

rdrf/explorer/templates/explorer/query_download.html
{% extends "explorer/base.html" %}

{% block content %}
    <script>
        $(document).ready(function() {
            $('input[id*=date_]').each(function() {
                $(this).prop('readonly', true);
                $(this).datepicker({
                    "dateFormat": "yy-mm-dd"
                });
            })
        });
    </script>

    {% if messages %}
        <div class="alert alert-danger">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        </div>
    {% endif %}
    
    <blockquote>
        <p>Required parameters for <i>{{form.title.value}}</i> report</p>
    </blockquote>
    {{user_curator}}
    <form name="params-form" class="form-horizontal" method="post">
        {% csrf_token %}
        {% for param in query_params %}
            <div class="form-group">
                <label for="id_{{param}}" class="col-sm-2 control-label">{{param|capfirst}}</label>
                <div class="col-sm-10">
                    {% if param = 'registry' %}
                        <select id="id_{{param}}" name="{{param}}" class="form-control">
                            <option value=-1>...</option>
                            {% for reg in registry %}
                                <option value={{reg.id}}>{{reg.name}}</option>
                            {% endfor %}
                        </select>
                    {% elif param = 'working_group' %}
                        <select id="id_{{param}}" name="{{param}}" class="form-control">
                            <option value=-1>...</option>
                            {% for wg in working_group %}
                                <option value={{wg.id}}>{{wg.name}}</option>
                            {% endfor %}
                        </select>
                    {% else %}
                        <input type="text" id="id_{{param}}" name="{{param}}" class="form-control">
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="form-group">

            {%  if action == "download" %}
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-success" type="submit">Download</button>
            </div>
            {%  endif %}

            {% if action == "view" %}
             <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-success" type="submit">View</button>
            </div>
            {% endif %}
        </div>
    </form>
{% endblock %}

rdrf/explorer/templates/explorer/query_list.html
{% extends "explorer/base.html" %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-3">Query</th>
                <th class="col-md-3">Download</th>
                <th class="col-md-3">View</th>
                <th class="col-md-3">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                {% if request.user.is_superuser %}
                    <td><a href="{% url 'explorer_query' object.id %}">{{ object }}</a></td>
                {% else %}
                    <td>{{object}}</td>
                {% endif %}
                <td>
                    <a href="{% url 'explorer_query_download' object.id "download" %}"><i class="glyphicon glyphicon-download" style="font-size: 20px;"></i></a>
                </td>
                 <td>
		   {% if object.has_view %}
                   <a href="{% url 'explorer_query_download' object.id "view" %}"><i class="glyphicon glyphicon-eye-open" style="font-size: 20px;"></i></a>
		   {% else %}
		   <span class="glyphicon glyphicon-large glyphicon-remove" style="color: red;font-size:1.5em;" aria-hidden="true"></span>
		   {% endif %}
                </td>
                <td>
                    {% if request.user.is_superuser %}
                        <i class="glyphicon glyphicon-trash" style="font-size: 18px;" onclick="$('#confirm_' + {{object.id}}).toggle()"></i>
                        <div style="display: none;" id="confirm_{{object.id}}">
                            Are you sure?
                            <a href="{% url 'explorer_query_delete' object.id %}">Yes</a> | 
                            <a onclick="$('#confirm_' + {{object.id}}).toggle()">No</a>
                        </div>
                    {% else %}
                        N/A
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}